### ISSUE TITLE
Doesn't call out to swap on Lorewalker Stonestep.

### ISSUE THREAD

**Issue by gotex007** [DeadlyBossMods/DBM-Dungeons#102] opened 2023-03-02 09:08 UTC
Since the update where it's supposed to call to swap at 7 stacks, it no longer calls it out even though the option to is enabled.

**Comment by MysticalOS** [comment] 2023-03-02 09:14
yeah i noticed that too, yet looked at code and found 0 issues with it, so it's not really fixable. it's literally coded to warn at 7 8 9 and 10 stacks by current code.

**Comment by MysticalOS** [comment] 2023-03-02 09:26
oh are you a healer? the update disabled it by default for healers

**Comment by gotex007** [comment] 2023-03-02 12:22
It didn't do it when I tanked the key right before creating this issue so I'm not sure it's just a healer thing. I can't remember if it did it as a dps earlier today but I don't think it did.

**Comment by MysticalOS** [comment] 2023-03-03 10:15
I can't seem to find any way to fix it, because the problem should have been utterly impossible.

Since there was no way to fix it though fixed it so the regular announce will now work at 8 stacks and not stop at 6.

**Comment by MysticalOS** [comment] 2023-03-03 19:45
it's possible this is fixed with an update to latest core. I'll try to test it later.

**Comment by MysticalOS** [comment] 2023-03-04 03:19
Confirmed fix in latest dbm core update so closing this

**Closed by MysticalOS** 2023-03-04 03:19 UTC

**Comment by gotex007** [comment] 2023-03-09 10:39
The TJS I just ran as tank with the new update didn't call out to swap again.

**Comment by MysticalOS** [comment] 2023-03-09 18:54
gonna assume you haven't updated DBM core or dbm dungeons one or the other. it calls it out just fine at 7 stacks

**Comment by gotex007** [comment] 2023-03-09 23:51
Wowup keeps everything automatically updated but I'll see when I go there next. Hopefully I'm wrong and it isn't having weird issue again.
