### ISSUE TITLE
Cant install on Curse Forge

### ISSUE THREAD

**Issue by razzz89** [DeadlyBossMods/DBM-Dungeons#60] opened 2022-08-11 10:45 UTC
after  finding dbm not working in shadowlands realised its been moved to  one mod i tried to install on curse forge but it dosnt seem to be installing after clicking the install  it unzips   and finishes but then the install is still lit  up as if not installed and it is not in my list of installed add on's i tried to download  it independantly but  it wont do that either it says couldn't download virus detected

**Comment by MysticalOS** [comment] 2022-08-11 15:48
Duplicate of #58 

It's a false flag. the file is fine so you ignore that warning.

**Closed by MysticalOS** 2022-08-11 15:48 UTC

**Comment by razzz89** [comment] 2022-08-11 22:04
I cant ignore it it wont download it  at all  my computer dosnt give me the choice to still download it just blocks it

**Comment by razzz89** [comment] 2022-08-11 22:08
so how do i  make my computer download it please ?
